// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestSyncProgress = { completed_note_ids: Array<bigint>, started_at: string, };
