// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestSummary = { markdown: string, max_new_tokens: number, recursive: boolean, };
