// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResponseHighlight = { id: string, from: number, to: number, selected_text: string, explanation: string, created_at: string, };
