// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResponseChoice } from "./ResponseChoice";

export type ResponseExplanation = { choices: Array<ResponseChoice>, };
