// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResponseAttachment = { id: bigint, path: string, content_type: string, created_at: string, last_updated: string, bytes: Array<number>, };
