// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResponseAuth = { access_token: string, refresh_token: string, user_id: string, is_active: boolean, username: string, email: string, };
