spring:
  application:
    name: backend
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:backend/.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/cognitum?currentSchema=cognitum_data&serverTimezone=UTC
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    database: postgresql
  mail:
    host: smtp.gmail.com
    port: 587
    username: cognitumapp@gmail.com
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      jwt-expiration: 86400000 # 24 hours
      refresh-token-expiration: 2419200000 # 1 month

app:
  is-dev-mode: true
  summarizer:
    client:
      base-url: http://localhost:8000

logging:
  level:
    org:
      springframework:
        security: DEBUG

nvidia:
  api:
    url: https://integrate.api.nvidia.com/v1
    model: meta/llama-3.3-70b-instruct
    key: ${NVIDIA_API_KEY}
